In [1]:
import numpy as np
from models import IRLS
import datasets.read as data

In [2]:
X, y = data.read_Rice_Cammeo_Osmancik("datasets/")

/home/klimek/sem8_v2/aml/aml_projects/Project1/datasets/read.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Class'] = df['Class'].replace('Osmancik', 0)


In [3]:
X.shape

(3810, 7)

In [4]:
np.isnan(X).sum()

0

In [5]:
X[:5,:]

array([[1.52310000e+04, 5.25578979e+02, 2.29749878e+02, 8.50937881e+01,
        9.28882003e-01, 1.56170000e+04, 5.72895527e-01],
       [1.46560000e+04, 4.94311005e+02, 2.06020065e+02, 9.17309723e+01,
        8.95404994e-01, 1.50720000e+04, 6.15436316e-01],
       [1.46340000e+04, 5.01122009e+02, 2.14106781e+02, 8.77682877e+01,
        9.12118077e-01, 1.49540000e+04, 6.93258822e-01],
       [1.31760000e+04, 4.58342987e+02, 1.93337387e+02, 8.74483948e+01,
        8.91860902e-01, 1.33680000e+04, 6.40669048e-01],
       [1.46880000e+04, 5.07166992e+02, 2.11743378e+02, 8.93124542e+01,
        9.06690896e-01, 1.52620000e+04, 6.46023929e-01]])

In [6]:
y.shape

(3810,)

In [7]:
np.isnan(y).sum()

0

In [8]:
y[:5]

array([1, 1, 1, 1, 1])

## IRLS test

In [9]:
m = IRLS(p=2)
m.fit(X, y)

In [10]:
y_pred = m.predict(X)
np.abs(y_pred - y).mean()

0.06929133858267716

In [11]:
np.all(m.get_params()['weights'] == np.diag(np.ones(X.shape[0])))

True

In [15]:
y_lodds = m.log_odds(X)
1/(1+np.exp(-y_lodds[y == 1][:10]))

array([0.87259497, 0.68490873, 0.74175585, 0.49207599, 0.77513176,
       0.58367509, 0.67424235, 0.82806011, 0.5761475 , 0.54872194])